name: vioai
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter_dotenv: ^5.0.2
  simple_gradient_text: ^1.2.4
  google_fonts: ^4.0.3
  logger: ^1.3.0
  flutter_svg: ^2.0.4
  injectable: ^2.1.1
  dartz: ^0.10.1
  get_it: ^7.2.0
  provider: ^6.0.5
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  retrofit: ^4.0.1
  auto_route: ^6.4.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  injectable_generator: ^2.1.5
  mockito: ^5.4.0
  retrofit_generator: ^6.0.0+1
  auto_route_generator: ^6.2.0
  change_app_package_name: ^1.1.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
