name: vioai
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter_bloc: ^8.1.2  
  flutter_dotenv: ^5.0.2
  simple_gradient_text: ^1.2.4
  google_fonts: ^4.0.3
  logger: ^1.3.0
  flutter_svg: ^2.0.4
  injectable: ^2.1.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  injectable_generator: ^2.1.5

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
